"use client";

import { useState, useEffect, useRef } from "react";
import Image from "next/image";
import { Style, StyleFormData } from "@/lib/styles";

interface StyleModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: StyleFormData) => Promise<void>;
  style?: Style | null;
  loading?: boolean;
}

export default function StyleModal({
  isOpen,
  onClose,
  onSave,
  style,
  loading = false,
}: StyleModalProps) {
  const [formData, setFormData] = useState<StyleFormData>({
    name: "",
    prompt: "",
    imageUrl: "",
    status: "Active",
    category: "",
    tags: [],
  });
  const [error, setError] = useState("");
  const [uploading, setUploading] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string>("");
  const [tagInput, setTagInput] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Generate unique style code
  const generateStyleCode = (): string => {
    const timestamp = Date.now();
    const randomStr = Math.random().toString(36).substring(2, 6).toUpperCase();
    return `STYLE-${timestamp}-${randomStr}`;
  };

  useEffect(() => {
    if (style) {
      // Edit mode: use existing style data
      setFormData({
        name: style.name,
        prompt: style.prompt,
        imageUrl: style.imageUrl,
        status: style.status,
        category: style.category || "",
        tags: style.tags || [],
      });
      setPreviewUrl(style.imageUrl);
    } else {
      // New style: auto-generate code
      const autoGeneratedCode = generateStyleCode();
      setFormData({
        name: autoGeneratedCode,
        prompt: "",
        imageUrl: "",
        status: "Active",
        category: "",
        tags: [],
      });
      setPreviewUrl("");
    }
    setError("");
    setTagInput("");
  }, [style, isOpen]);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith("image/")) {
      setError("Please select an image file");
      return;
    }

    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      setError("Image size must be less than 5MB");
      return;
    }

    try {
      setUploading(true);
      setError("");

      // Create preview URL for immediate display
      const localPreview = URL.createObjectURL(file);
      setPreviewUrl(localPreview);

      // Upload to local server (public/uploads/styles/)
      const uploadFormData = new FormData();
      uploadFormData.append("file", file);
      uploadFormData.append("type", "style");

      const response = await fetch("/api/upload", {
        method: "POST",
        body: uploadFormData,
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({
          error: `HTTP ${response.status}`,
        }));
        throw new Error(errorData.error || "Failed to upload image");
      }

      const data = await response.json();

      if (!data.ok || !data.url) {
        throw new Error(data.error || "Failed to upload image");
      }

      // Update form data with the uploaded image URL
      const imageUrl = data.url;
      setFormData({ ...formData, imageUrl: imageUrl });

      // Update preview URL to use the uploaded image
      setPreviewUrl(imageUrl);

      // Clean up local preview URL
      URL.revokeObjectURL(localPreview);
      
      console.log("Image uploaded successfully:", imageUrl);
    } catch (error: any) {
      console.error("Error uploading image:", error);
      setError(error.message || "Failed to upload image");
      setPreviewUrl("");
      // Clean up preview URL on error
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    } finally {
      setUploading(false);
    }
  };

  const handleAddTag = () => {
    const trimmedTag = tagInput.trim();
    if (trimmedTag && !formData.tags?.includes(trimmedTag)) {
      setFormData({
        ...formData,
        tags: [...(formData.tags || []), trimmedTag],
      });
      setTagInput("");
    }
  };

  const handleRemoveTag = (tagToRemove: string) => {
    setFormData({
      ...formData,
      tags: formData.tags?.filter((tag) => tag !== tagToRemove) || [],
    });
  };

  const handleTagInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      e.preventDefault();
      handleAddTag();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    // Debug: Log form data
    console.log("Form submission - formData:", formData);

    if (!formData.name.trim()) {
      setError("Style name is required");
      return;
    }

    if (!formData.prompt.trim()) {
      setError("Prompt is required");
      return;
    }

    if (!formData.imageUrl || !formData.imageUrl.trim()) {
      setError("Preview image is required. Please upload an image or enter a URL.");
      return;
    }

    try {
      await onSave(formData);
      onClose();
    } catch (error: any) {
      setError(error.message || "Failed to save style");
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="w-full max-w-4xl rounded-xl bg-[#242424] p-6 shadow-2xl max-h-[90vh] overflow-y-auto">
        <div className="mb-6 flex items-center justify-between">
          <h2 className="text-2xl font-bold text-white">
            {style ? "Edit Style" : "Add New Style"}
          </h2>
          <button
            onClick={onClose}
            className="text-white/70 hover:text-white transition-colors"
            disabled={loading || uploading}
          >
            <span className="material-symbols-outlined text-2xl">close</span>
          </button>
        </div>

        {error && (
          <div className="mb-4 rounded-lg bg-red-500/20 border border-red-500/50 p-3 text-sm text-red-400">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6" noValidate>
          {/* 2 Column Layout */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Left Column */}
            <div className="space-y-4">
              {/* Style Name - Hidden, auto-generated */}
            <input
                type="hidden"
              value={formData.name}
              required
            />

              {/* Category */}
              <div className="flex flex-col">
                <label
                  className="mb-2 text-sm font-medium text-[#EAEAEA]"
                  htmlFor="category"
                >
                  Category
                </label>
                <input
                  className="form-input h-12 w-full rounded-lg border-none bg-[#1A1A1A] p-3 text-base text-white placeholder:text-[#888888] focus:outline-none focus:ring-2 focus:ring-primary"
                  id="category"
                  placeholder="e.g., Nature, Urban, Abstract"
                  type="text"
                  value={formData.category || ""}
                  onChange={(e) =>
                    setFormData({ ...formData, category: e.target.value })
                  }
                  disabled={loading || uploading}
                />
              </div>

              {/* Status */}
          <div className="flex flex-col">
                <label
                  className="mb-2 text-sm font-medium text-[#EAEAEA]"
                  htmlFor="status"
                >
              Status <span className="text-red-400">*</span>
            </label>
            <select
              className="form-input h-12 w-full rounded-lg border-none bg-[#1A1A1A] p-3 text-base text-white focus:outline-none focus:ring-2 focus:ring-primary"
              id="status"
              value={formData.status}
              onChange={(e) =>
                setFormData({
                  ...formData,
                  status: e.target.value as "Active" | "Inactive",
                })
              }
              required
                  disabled={loading || uploading}
            >
                  <option value="Active">Active</option>
                  <option value="Inactive">Inactive</option>
                </select>
              </div>

              {/* Tags */}
              <div className="flex flex-col">
                <label
                  className="mb-2 text-sm font-medium text-[#EAEAEA]"
                  htmlFor="tags"
                >
                  Tags
                </label>
                <div className="flex gap-2 mb-2">
                  <input
                    className="form-input h-10 flex-1 rounded-lg border-none bg-[#1A1A1A] p-3 text-sm text-white placeholder:text-[#888888] focus:outline-none focus:ring-2 focus:ring-primary"
                    id="tags"
                    placeholder="Add a tag and press Enter"
                    type="text"
                    value={tagInput}
                    onChange={(e) => setTagInput(e.target.value)}
                    onKeyDown={handleTagInputKeyDown}
                    disabled={loading || uploading}
                  />
                  <button
                    type="button"
                    onClick={handleAddTag}
                    className="h-10 px-4 rounded-lg bg-primary text-white hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    disabled={loading || uploading || !tagInput.trim()}
                  >
                    <span className="material-symbols-outlined text-lg">add</span>
                  </button>
                </div>
                {formData.tags && formData.tags.length > 0 && (
                  <div className="flex flex-wrap gap-2">
                    {formData.tags.map((tag) => (
                      <span
                        key={tag}
                        className="inline-flex items-center gap-1 px-3 py-1 rounded-full bg-primary/20 text-primary text-sm"
                      >
                        {tag}
                        <button
                          type="button"
                          onClick={() => handleRemoveTag(tag)}
                          className="hover:text-primary/70 transition-colors"
                          disabled={loading || uploading}
                        >
                          <span className="material-symbols-outlined text-sm">
                            close
                          </span>
                        </button>
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Right Column - Image Upload & Preview */}
            <div className="flex flex-col">
              <label className="mb-2 text-sm font-medium text-[#EAEAEA]">
                Preview Image <span className="text-red-400">*</span>
              </label>
              <div className="flex flex-col gap-3">
                {/* Upload Button */}
                <div className="relative">
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handleFileChange}
                    className="hidden"
                    disabled={loading || uploading}
                  />
                  <button
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full h-12 rounded-lg border-2 border-dashed border-white/20 bg-[#1A1A1A] text-white hover:border-primary hover:bg-[#1A1A1A]/80 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                    disabled={loading || uploading}
                  >
                    {uploading ? (
                      <>
                        <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-r-transparent"></div>
                        <span>Uploading...</span>
                      </>
                    ) : (
                      <>
                        <span className="material-symbols-outlined">upload</span>
                        <span>Upload Image</span>
                      </>
                    )}
                  </button>
                </div>

                {/* Image Preview */}
                {previewUrl ? (
                  <div className="relative aspect-square w-full overflow-hidden rounded-lg border border-white/10 bg-[#1A1A1A]">
                    <Image
                      src={previewUrl}
                      alt="Preview"
                      fill
                      className="object-cover"
                      unoptimized
                      onError={() => {
                        setPreviewUrl("");
                        setError("Failed to load image preview");
                      }}
                    />
                    {formData.imageUrl && (
                      <div className="absolute top-2 right-2">
                        <span className="inline-flex items-center gap-1 px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs">
                          <span className="material-symbols-outlined text-sm">
                            check_circle
                          </span>
                          Uploaded
                        </span>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="aspect-square w-full rounded-lg border border-white/10 bg-[#1A1A1A] flex items-center justify-center">
                    <div className="text-center text-white/30">
                      <span className="material-symbols-outlined text-4xl mb-2 block">
                        image
                      </span>
                      <p className="text-sm">No preview available</p>
                    </div>
                  </div>
                )}

                {/* Manual URL Input (Alternative) */}
                <div className="flex flex-col">
                  <label className="mb-1 text-xs text-white/50">
                    Or enter image URL manually
                  </label>
                  <input
                    className="form-input h-10 w-full rounded-lg border-none bg-[#1A1A1A] p-2 text-sm text-white placeholder:text-[#888888] focus:outline-none focus:ring-2 focus:ring-primary"
                    placeholder="https://example.com/image.jpg or /uploads/styles/image.jpg"
                    type="text"
                    value={formData.imageUrl}
                    onChange={(e) => {
                      setFormData({ ...formData, imageUrl: e.target.value });
                      if (e.target.value) {
                        setPreviewUrl(e.target.value);
                      }
                    }}
                    disabled={loading || uploading}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* AI Prompt - Full Width */}
          <div className="flex flex-col">
            <label
              className="mb-2 text-sm font-medium text-[#EAEAEA]"
              htmlFor="prompt"
            >
              AI Prompt <span className="text-red-400">*</span>
            </label>
            <textarea
              className="form-input min-h-[120px] w-full resize-none rounded-lg border-none bg-[#1A1A1A] p-3 text-base text-white placeholder:text-[#888888] focus:outline-none focus:ring-2 focus:ring-primary"
              id="prompt"
              placeholder="Enter the prompt that will be used for image generation..."
              value={formData.prompt}
              onChange={(e) =>
                setFormData({ ...formData, prompt: e.target.value })
              }
              required
              disabled={loading || uploading}
            />
            <p className="mt-1 text-xs text-white/50">
              This prompt will be used when users select this style
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4 pt-4 border-t border-white/10">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 h-12 rounded-lg border border-white/10 bg-[#1A1A1A] px-4 py-2 text-base font-medium text-white transition-colors hover:bg-white/5 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={loading || uploading}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex-1 h-12 rounded-lg bg-primary px-4 py-2 text-base font-bold text-white transition-colors hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={loading || uploading}
            >
              {loading ? "Saving..." : style ? "Update Style" : "Create Style"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
